Repository next-step/js-todo-list-step2, pull requests merged in 2020-10, with the labels that each got.

#16 [3기 JunilHwang] TodoList with Ajax
  .gitignore
  README.md
  css/app.css
  index.html
  src/App.js
  src/adapter/todoAdapter.js
  src/components/Todo/TodoAppender.js
  src/components/Todo/TodoFooter.js
  src/components/Todo/TodoList.js
  src/components/User/UserList.js
  src/components/User/UserTitle.js
  src/constants/FilterTypes.js
  src/constants/HttpMethod.js
  src/constants/LoadingTypes.js
  src/constants/PriorityTypes.js
  src/containers/TodoContainer.js
  src/containers/UserContainer.js
  src/core/Component.js
  src/core/Observer.js
  src/core/RestClient.js
  src/core/Store.js
  src/services/TodoService.js
  src/store/todoStore.js
  src/store/userStore.js
  src/utils/index.js
Labels: TeamA, 🚀 필수미션, 🚀 🚀 추가미션, 🚨 리뷰 요청

#17 [3기 이한솔]TodoList with Ajax
  css/app.css
  index.html
  js/components/TodoApp.js
  js/components/TodoFooter.js
  js/components/TodoInput.js
  js/components/TodoList.js
  js/components/UserList.js
  js/components/UserTitle.js
  js/data/Error.js
  js/data/HttpMethod.js
  js/data/Priorities.js
  js/data/constant.js
  js/observer/Observer.js
  js/observer/Subject.js
  js/repository/HttpClient.js
  js/repository/TodoHttpClient.js
  js/repository/TodoHttpClientAdapter.js
  js/service/UserService.js
  js/utils/functionalJS.js
Labels: TeamA, 🚀 필수미션, 🚨 리뷰 요청

#18 [3기 전환오] TodoList with Ajax
  .gitignore
  .prettierrc
  README.md
  css/app.css
  index.html
  index.js
  js/components/App.js
  js/components/TodoClearBtn.js
  js/components/TodoCount.js
  js/components/TodoFilter.js
  js/components/TodoInput.js
  js/components/TodoList.js
  js/components/UserList.js
  js/components/UserTitle.js
  js/constant/index.js
  js/core/Component.js
  js/core/State.js
  js/index.js
  js/templates/loadingBar.js
  js/templates/todoItem.js
  js/templates/userButton.js
  js/util/index.js
  package-lock.json
  package.json
Labels: TeamA, 🚀 필수미션, 🚀 🚀 추가미션, 🚨 리뷰 요청

#19 [3기 김종완] TodoList with Ajax
  .gitignore
  README.md
  index.html
  js/components/todo/TodoCount.js
  js/components/todo/TodoInput.js
  js/components/todo/TodoList.js
  js/components/user/UserList.js
  js/components/user/UserTitle.js
  js/constants/constants.js
  js/core/Component.js
  js/index.js
  js/service/UserApi.js
  js/service/core.js
Labels: TeamB, 🚀 필수미션, 🚀 🚀 추가미션, 🚨 리뷰 요청

#20 [3기 dotol] TodoList with Ajax
  README.md
  css/app.css
  index.html
  js/TodoState.js
  js/component/todoCount.js
  js/component/todoInput.js
  js/component/todoList.js
  js/component/userList.js
  js/index.js
  js/util/fetchParams.js
  js/util/fetcher.js
  js/util/httpMethod.js
  js/util/urls.js
  js/util/util.js
Labels: TeamB, 🚀 필수미션, 🚀 🚀 추가미션, 🚨 리뷰 요청

#22 [3기 김동하] TodoList with Ajax
  .gitignore
  index-copy.html
  index.html
  js/api/index.js
  js/components/TodoFooter.js
  js/components/TodoItem.js
  js/components/TodoList.js
  js/components/TodoSkeleton.js
  js/components/UserButton.js
  js/components/UserList.js
  js/components/UserTitle.js
  js/constant.js
  js/container/InputContainer.js
  js/container/TodoFooterContainer.js
  js/container/TodoListContainer.js
  js/container/UserListContainer.js
  js/container/UserTitleContainer.js
  js/index.js
  js/reducer.js
  js/redux.js
Labels: TeamB, 🚀 필수미션, 🚀 🚀 추가미션, 🚨 리뷰 요청

#23 [3기 나무] TodoList with Ajax
  .eslintrc.js
  .gitignore
  README.md
  css/app.css
  index.html
  js/API.js
  js/TodoCount.js
  js/TodoFilter.js
  js/TodoInput.js
  js/TodoList.js
  js/TodoUser.js
  js/app.js
  js/constants.js
  js/validation.js
Labels: TeamC, ❓질문, 🐞 버그
