Repository next-step/js-todo-list-step2, pull requests merged in 2020-12, with the labels that each got.

#27 [4기 박병길] TodoList with Ajax
  .vscode/settings.json
  README.md
  index.html
  js/api/todoApi.js
  js/api/userApi.js
  js/components/App.js
  js/components/TodoInput.js
  js/components/TodoList.js
  js/components/UserList.js
  js/index.js
  js/store/Store.js
  js/utils/api.js
  js/utils/constant.js
  js/utils/templates.js
  js/utils/validator.js
Labels: TeamA, 🚀 필수미션, 🚨 리뷰 요청

#24 [4기 박은영] TodoList with Ajax
  .gitignore
  README.md
  index.html
  js/index.js
  src/app.js
  src/constants/filter.js
  src/constants/messageAPI.js
  src/core/state.js
  src/css/app.css
  src/endpoint/HttpMethod.js
  src/endpoint/RestApi.js
  src/endpoint/facade.js
  src/endpoint/user/api.js
  src/endpoint/user/controller.js
  src/env.js
  src/eventHandler.js
  src/store/index.js
  src/template/Todo/TodoContainer.js
  src/template/Todo/TodoCount.js
  src/template/Todo/TodoCountContainer.js
  src/template/Todo/TodoFilter.js
  src/template/Todo/TodoInput.js
  src/template/Todo/TodoItem.js
  src/template/Todo/TodoLabel.js
  src/template/Todo/TodoList.js
  src/template/Todo/TodoLoading.js
  src/template/User/UserList.js
  src/template/User/UserListContainer.js
  src/template/User/UserTitle.js
  src/template/index.js
  src/utils.js
  src/validator.js
Labels: TeamA, 🚀 필수미션, 🚀 🚀 추가미션, 🚨 리뷰 요청

#30 [레벨1 4기 나나] TodoList with Ajax
  js/client/userService.js
  js/components/render.js
  js/components/selectedUser.js
  js/index.js
Labels: TeamA, 🚀 필수미션, 🚨 리뷰 요청

#31 [레벨1 4기 younho9] TodoList with Ajax
  README.md
  css/app.css
  index.html
  js/api/apis.js
  js/api/index.js
  js/components/App.js
  js/components/FilterItem.js
  js/components/TodoContainer.js
  js/components/TodoFooter.js
  js/components/TodoInput.js
  js/components/TodoItem.js
  js/components/TodoList.js
  js/components/UserContainer.js
  js/components/UserItem.js
  js/components/UserList.js
  js/components/UserTitle.js
  js/constants/index.js
  js/core/createElement.js
  js/core/eventChannel.js
  js/index.js
  js/store.js
  js/utils/index.js
  js/utils/validators.js
Labels: TeamB, 🚀 필수미션, 🚀 🚀 추가미션, 🚨 리뷰 요청

#32 [4기 one] TodoList with Ajax
  index.html
  js/index.js
  src/App.js
  src/shared/utils/constants.js
  src/shared/utils/repository.js
  src/todo/api/index.js
  src/todo/components/TodoCount.js
  src/todo/components/TodoCreateUserButton.js
  src/todo/components/TodoDeleteUserButton.js
  src/todo/components/TodoInput.js
  src/todo/components/TodoList.js
  src/todo/components/TodoUserInput.js
  src/todo/components/TodoUserList.js
  src/todo/components/index.js
  src/todo/css/app.css
  src/todo/index.js
  src/todo/stores/index.js
  src/todo/stores/todoStore.js
  src/todo/utils/event.js
  src/todo/utils/validator.js
Labels: TeamB, 🚀 필수미션, 🚀 🚀 추가미션, 🚨 리뷰 요청

#35 [5기 Junho] TodoList with Ajax
  babel.config.js
  css/app.css
  index.html
  js/components/App.js
  js/components/Task.js
  js/components/User.js
  js/index.js
  js/render.js
  js/util/api.test.js
  js/util/index.js
  js/util/request.js
Labels: TeamA, 🚀 필수미션, 🚀 🚀 추가미션, 🚨 리뷰 요청
