Repository next-step/js-todo-list-step2, pull requests merged in 2021-02, with the labels that each got.

#34 [5기 김수정] TodoList with Ajax
  README.md
  css/app.css
  index.html
  js/index.js
  src/components/Loading.js
  src/components/TodoBottom.js
  src/components/TodoInput.js
  src/components/TodoList.js
  src/components/TodoListTitle.js
  src/components/UserList.js
  src/components/index.js
  src/configs/server.js
  src/connectors/TodoConnector.js
  src/constants/Filter.js
  src/constants/HttpMethods.js
  src/constants/TodoPriority.js
  src/constants/TodoPriorityClassName.js
  src/core/Component.js
  src/core/HttpConnector.js
  src/core/redux-saga/index.js
  src/core/redux-saga/redux-saga.js
  src/core/redux/index.js
  src/core/redux/redux.js
  src/helper/reduxHelper.js
  src/helper/userHelper.js
  src/index.js
  src/modules/index.js
  src/modules/user/actions.js
  src/modules/user/index.js
  src/modules/user/reducer.js
  src/modules/user/saga.js
Labels: TeamA, 🚀 필수미션, 🚀 🚀 추가미션, 🚨 리뷰 요청

#36 [5기 한정원] TodoList with Ajax
  .prettierrc
  README.md
  css/app.css
  index.html
  js/common/message.js
  js/common/validate.js
  js/components/todoList/count.js
  js/components/todoList/deleteAll.js
  js/components/todoList/filter.js
  js/components/todoList/input.js
  js/components/todoList/list.js
  js/components/todoList/listComponent.js
  js/components/user/user.js
  js/components/user/userName.js
  js/index.js
  js/lib/api.js
  js/lib/component.js
  js/lib/pubsub.js
  js/store/action.js
  js/store/index.js
  js/store/state.js
  js/store/store.js
Labels: TeamA, 🚀 필수미션, 🚀 🚀 추가미션, 🚨 리뷰 요청

#37 [5기 김우정] TodoList with Ajax
  .gitignore
  .vscode/settings.json
  css/app.css
  img/bin.png
  index.html
  js/App.js
  js/api/settings.js
  js/api/todoAPI.js
  js/components/TodoApp.js
  js/components/TodoCount.js
  js/components/TodoInput.js
  js/components/TodoList.js
  js/components/UserList.js
  js/components/UserTitle.js
  js/index.js
Labels: TeamB, 🚀 필수미션, 🚀 🚀 추가미션, 🚨 리뷰 요청

#39 [5기 WOO] TodoList with Ajax
  .gitignore
  README.md
  css/app.css
  index.html
  js/App.js
  js/api/index.js
  js/api/utils/constant.js
  js/component/TodoCount.js
  js/component/TodoFilter.js
  js/component/TodoFilterItem.js
  js/component/TodoInput.js
  js/component/TodoList.js
  js/component/TodoListItem.js
  js/component/UserList.js
  js/component/UserListItem.js
  js/component/UserTitle.js
  js/core/Component.js
  js/index.js
  js/store/index.js
  js/store/module/filter.js
  js/store/module/todo.js
  js/store/module/user.js
  js/utils/constants.js
  js/utils/watch.js
Labels: TeamB, 🚀 필수미션, 🚀 🚀 추가미션, 🚨 리뷰 요청

#40 [5기 김민식] TodoList with Ajax
  index.html
  js/component/App.js
  js/component/Common.js
  js/component/Render.js
  js/component/Server.js
  js/component/User.js
  js/index.js
Labels: TeamB
