Repository next-step/js-todo-list-step2, pull requests merged in 2021-03, with the labels that each got.

#43 [6기 Suppplier] TodoList with Ajax
  index.html
  js/AddNewItem.js
  js/AjaxDelete.js
  js/AjaxGet.js
  js/AjaxPost.js
  js/AjaxPut.js
  js/ControlTodoButton.js
  js/ControlTodoItems.js
  js/ControlUserList.js
  js/index.js
Labels: TeamA, 🚀 필수미션, 🚀 🚀 추가미션, 🚨 리뷰 요청

#44 [6기 Kwonkyu] TodoList with Ajax
  css/app.css
  index.html
  js/application.js
  js/common.js
  js/filterview.js
  js/index.js
  js/todolistview.js
  js/users.js
Labels: TeamA, 🏆 미션완료, 🚨 리뷰 요청

#45 [6기 조윤호] TodoList with Ajax
  .eslintrc.json
  .gitignore
  .prettierrc
  README.md
  css/app.css
  index.html
  js/index.js
  package-lock.json
  package.json
  src/api/api.js
  src/components/todoList/addTodo.js
  src/components/todoList/changePriority.js
  src/components/todoList/deleteAllTodo.js
  src/components/todoList/deleteTodo.js
  src/components/todoList/editTodo.js
  src/components/todoList/filterTodo.js
  src/components/todoList/loadTodos.js
  src/components/todoList/todoList.js
  src/components/todoList/toggleTodo.js
  src/components/userList/addUser.js
  src/components/userList/deleteUser.js
  src/components/userList/loadUsers.js
  src/components/userList/selectUser.js
  src/components/userList/userList.js
  src/constant/api.js
  src/constant/todo.js
  src/constant/user.js
  src/index.js
  src/utils/localStorage.js
Labels: TeamA, 🚀 필수미션, 🚀 🚀 추가미션, 🚨 리뷰 요청

#46 [6기 khw970421] TodoList with Ajax
  index.html
  js/AddTodolistItem.js
  js/Server.js
  js/index.js
Labels: TeamB, 🚀 필수미션, 🚨 리뷰 요청

#49 [6기 김동환] TodoList with Ajax
  api/index.js
  components/TodoApp.js
  components/TodoInput.js
  components/TodoList.js
  components/TodoTotalCount.js
  components/TodoUsers.js
  index.html
  js/index.js
  js/user.service.js
  js/util.js
Labels: TeamC, 🚀 필수미션, 🚀 🚀 추가미션, 🚨 리뷰 요청

#50 [6기 시경덕] TodoList with Ajax
  .gitignore
  css/app.css
  index.html
  js/apis.js
  js/components/TodoApp.js
  js/components/TodoCount.js
  js/components/TodoInput.js
  js/components/TodoList.js
  js/components/TodoUser.js
  js/index.js
  js/utils.js
Labels: TeamC, 🏆 미션완료, 🚀 필수미션, 🚨 리뷰 요청

#51 [6기 박소현] TodoList with Ajax
  .eslintrc.json
  .gitignore
  .prettierrc
  .vscode/settings.json
  index.html
  js/index.js
  package-lock.json
  package.json
  src/App.js
  src/api/api.js
  src/components/Loading.js
  src/components/Title.js
  src/components/TodoInput.js
  src/components/TodoItem.js
  src/components/Todolist.js
  src/components/TodolistFooter.js
  src/components/UserAddButton.js
  src/components/UserDeleteButton.js
  src/components/UserItem.js
  src/components/UserList.js
  src/components/index.js
  src/css/app.css
  src/index.html
  src/index.js
  src/modules/selectedUser.js
  src/modules/users.js
  src/store/Store.js
Labels: TeamC, 🚀 필수미션, 🚀 🚀 추가미션, 🚨 리뷰 요청

#52 [6기 Jiseon Kim] TodoList with Ajax
  .vscode/settings.json
  README.md
  css/app.css
  index.html
  js/index.js
  src/api.js
  src/app.js
  src/components/todo.js
  src/components/todoList.js
  src/components/todoTitle.js
  src/components/user.js
  src/main.js
  src/template.js
  src/todoDOM.js
Labels: TeamD, 🚀 필수미션, 🚨 리뷰 요청

#53 [6기 hongjehong] TodoList with Ajax
  .gitignore
  README.md
  css/app.css
  index.html
  js/API.js
  js/index.js
  js/template.js
  package-lock.json
  package.json
Labels: TeamD, 🚀 필수미션, 🚨 리뷰 요청

#55 [6기 pul8219] TodoList with Ajax
  README.md
  index.html
  js/api.js
  js/index.js
  js/localStorage.js
  js/todoList/addTodo.js
  js/todoList/checkTodo.js
  js/todoList/deleteTodo.js
  js/todoList/editTodo.js
  js/todoList/filterTodo.js
  js/todoList/loadTodos.js
  js/todoList/todoTrigger.js
  js/userList/addUser.js
  js/userList/deleteUser.js
  js/userList/loadUsers.js
  js/userList/selectUser.js
  js/userList/userListManage.js
Labels: TeamE, 🚨 리뷰 요청

#56 [6기 yeewon] TodoList with Ajax
  .eslintrc.json
  .prettierrc
  .vscode/settings.json
  css/app.css
  index.html
  js/index.js
  src/api/api.js
  src/components/todoList/addTodo.js
  src/components/todoList/controlTodo.js
  src/components/todoList/deleteAllTodos.js
  src/components/todoList/editPriority.js
  src/components/todoList/editTodo.js
  src/components/todoList/filterTodo.js
  src/components/todoList/loadTodos.js
  src/components/todoList/todoList.js
  src/components/todoList/todoTemplates.js
  src/components/userList/addUser.js
  src/components/userList/deleteUser.js
  src/components/userList/loadUsers.js
  src/components/userList/selectUser.js
  src/components/userList/userList.js
  src/components/userList/userTemplates.js
  src/index.js
  src/utils/localStorage.js
Labels: 🏆 미션완료, 🚀 필수미션, 🚀 🚀 추가미션, 🚨 리뷰 요청

#57 [7기 YunNote] TodoList with Ajax
  css/app.css
  index.html
  js/components/todo/TodoApp.js
  js/components/todo/TodoCount.js
  js/components/todo/TodoInput.js
  js/components/todo/TodoItem.js
  js/components/todo/TodoRemoveAll.js
  js/components/users/User.js
  js/components/users/UserList.js
  js/index.js
  js/utils/APIs.js
  js/utils/Filter.js
  js/utils/Key.js
  js/utils/PriorityFIlter.js
  js/utils/Request.js
  js/utils/Selector.js
  js/utils/Urls.js
  js/utils/Validation.js
Labels: TeamA, 🏆 미션완료, 🚀 필수미션, 🚀 🚀 추가미션, 🚨 리뷰 요청

#58 [7기 윤성학] TodoList with Ajax
  .gitignore
  README.md
  css/app.css
  index.html
  js/TodoApp.js
  js/api/index.js
  js/api/modules/member.js
  js/api/modules/todoItem.js
  js/controller/TodoFilterController.js
  js/controller/TodoItemController.js
  js/controller/TodoMemberController.js
  js/controller/TodoPrirorityController.js
  js/controller/TodoWriterController.js
  js/core/member.js
  js/index.js
  js/service/TodoFilterService.js
  js/service/TodoItemService.js
  js/service/TodoMemberSerivce.js
  js/service/TodoPrioritySerivce.js
  js/service/TodoWriterService.js
  js/store/index.js
  js/store/modules/member.js
  js/store/modules/todoItem.js
  js/utils/constants.js
  js/utils/priorityConverter.js
  js/utils/templates.js
  js/utils/util.js
  js/view/TodoView.js
  js/view/loadingbar.js
Labels: TeamA, 🏆 미션완료, 🚀 필수미션, 🚀 🚀 추가미션, 🚨 리뷰 요청

#59 [7기 정윤호] TodoList with Ajax
  css/app.css
  index.html
  js/index.js
  src/api/api.js
  src/constant/constants.js
  src/constant/message.js
  src/controller/todoFilterController.js
  src/controller/todoInputController.js
  src/controller/todoListController.js
  src/controller/userListController.js
  src/index.js
  src/layout/templates.js
  src/model/todoStore.js
  src/model/userStore.js
  src/utils/dom.js
  src/validator/validator.js
  src/view/todoFilterView.js
  src/view/todoInputView.js
  src/view/todoListView.js
  src/view/userListView.js
Labels: TeamA, 🏆 미션완료, 🚀 필수미션, 🚀 🚀 추가미션, 🚨 리뷰 요청

#60 [7기 inhyuck] TodoList with Ajax
  .gitignore
  apis/defaultApi.js
  apis/todoApi.js
  apis/userApi.js
  components/TodoApp.js
  components/TodoList.js
  components/UserList.js
  components/todoInput.js
  consts/priorityType.js
  index.html
  js/index.js
Labels: TeamB, 🏆 미션완료, 🚀 필수미션, 🚀 🚀 추가미션, 🚨 리뷰 요청

#62 [7기 임수지] TodoList with Ajax
  README.md
  css/app.css
  index.html
  js/index.js
  js/store.js
  js/todoApp.js
  js/todoInput.js
  js/todoList.js
  js/todoStatus.js
  js/userList.js
  js/util.js
Labels: TeamB, 🏆 미션완료, 🚀 필수미션, 🚀 🚀 추가미션, 🚨 리뷰 요청
